- name: Clone Proxmox VM
  hosts: edu1
  gather_facts: false
  vars_files:
    - vars.json

  tasks:
    - name: Check number of clones
      fail:
        msg: "Number of VMs in JSON exceeds the limit of 50"
      when: vms | length > 50

    - name: Clone VMs from template
      proxmox_kvm:
        api_host: "{{ ansible_host }}"
        api_user: "{{ ansible_user }}"
        api_password: "{{ ansible_password }}"
        validate_certs: false
        node: "edu1"
        vmid: "{{ item.vmid }}"
        name: "{{ item.vmname }}"
        clone: 117
        state: present
      with_items: "{{ vms }}"
